package dhrlang.tools;

import dhrlang.evm.EvmContractCompiler.ContractArtifact;

import java.util.*;

/**
 * Generates integration configs for external Ethereum development frameworks.
 *
 * <p>Supports:
 * <ul>
 *   <li><b>Foundry</b> — forge build integration, test templates, deploy scripts</li>
 *   <li><b>Hardhat</b> — task definitions, deploy scripts, test helpers</li>
 *   <li><b>Wagmi/Viem</b> — TypeScript contract bindings</li>
 * </ul>
 */
public final class FrameworkIntegration {

    private FrameworkIntegration() {}

    // ═══════════════════════════════════════════════════════════════
    //  Foundry Integration
    // ═══════════════════════════════════════════════════════════════

    /**
     * Generate a foundry.toml config that includes DhrLang compilation.
     */
    public static String foundryConfig(String projectName) {
        return """
                [profile.default]
                src = "contracts"
                out = "build/evm"
                libs = ["lib"]
                
                # DhrLang compiler integration
                [profile.default.dhrlang]
                compiler = "java -jar DhrLang.jar"
                extensions = ["dhr"]
                
                [fmt]
                line_length = 100
                
                [rpc_endpoints]
                sepolia = "${SEPOLIA_RPC_URL}"
                mainnet = "${MAINNET_RPC_URL}"
                arbitrum = "https://arb1.arbitrum.io/rpc"
                base = "https://mainnet.base.org"
                
                [etherscan]
                sepolia = { key = "${ETHERSCAN_API_KEY}" }
                mainnet = { key = "${ETHERSCAN_API_KEY}" }
                """;
    }

    /**
     * Generate a Foundry test template for a DhrLang contract.
     */
    public static String foundryTest(ContractArtifact artifact) {
        String name = artifact.getContractName();
        return """
                // SPDX-License-Identifier: MIT
                // Auto-generated by DhrLang for Foundry integration
                pragma solidity ^0.8.20;
                
                import "forge-std/Test.sol";
                
                contract %sTest is Test {
                    address public contractAddr;
                
                    function setUp() public {
                        // Deploy using DhrLang-compiled bytecode
                        bytes memory bytecode = hex"%s";
                        address deployed;
                        assembly {
                            deployed := create(0, add(bytecode, 0x20), mload(bytecode))
                        }
                        require(deployed != address(0), "Deployment failed");
                        contractAddr = deployed;
                    }
                
                    function testDeployment() public view {
                        assertTrue(contractAddr != address(0));
                        assertTrue(contractAddr.code.length > 0);
                    }
                
                    function testGasEstimate() public {
                        uint256 gasBefore = gasleft();
                        // Call a view function via low-level call
                        (bool success, ) = contractAddr.staticcall("");
                        uint256 gasUsed = gasBefore - gasleft();
                        emit log_named_uint("Gas used for empty call", gasUsed);
                        // No assertion — just measuring
                    }
                }
                """.formatted(name, artifact.getCreationBytecodeHex());
    }

    /**
     * Generate a Makefile for Foundry + DhrLang workflow.
     */
    public static String foundryMakefile() {
        return """
                # DhrLang + Foundry Makefile
                
                DHRLANG_JAR := DhrLang.jar
                CONTRACTS := $(wildcard contracts/*.dhr)
                
                .PHONY: compile audit deploy test clean
                
                compile:
                \t@echo "Compiling DhrLang contracts..."
                \t@for f in $(CONTRACTS); do \\
                \t\tjava -jar $(DHRLANG_JAR) contract compile "$$f"; \\
                \tdone
                
                audit:
                \t@echo "Running security audit..."
                \t@for f in $(CONTRACTS); do \\
                \t\tjava -jar $(DHRLANG_JAR) --audit "$$f"; \\
                \tdone
                
                audit-sarif:
                \t@mkdir -p build/sarif
                \t@for f in $(CONTRACTS); do \\
                \t\tjava -jar $(DHRLANG_JAR) --audit --sarif --output=build/sarif "$$f"; \\
                \tdone
                
                gas:
                \t@for f in $(CONTRACTS); do \\
                \t\tjava -jar $(DHRLANG_JAR) contract gas "$$f"; \\
                \tdone
                
                deploy-local:
                \t@echo "Deploying to local Anvil..."
                \t@for f in $(CONTRACTS); do \\
                \t\tjava -jar $(DHRLANG_JAR) contract deploy --network=local "$$f"; \\
                \tdone
                
                deploy-sepolia:
                \t@for f in $(CONTRACTS); do \\
                \t\tjava -jar $(DHRLANG_JAR) contract deploy --network=sepolia --dry-run "$$f"; \\
                \tdone
                
                test:
                \tforge test -vvv
                
                clean:
                \trm -rf build/evm build/sarif
                """;
    }

    // ═══════════════════════════════════════════════════════════════
    //  Hardhat Integration
    // ═══════════════════════════════════════════════════════════════

    /**
     * Generate a hardhat.config.js with DhrLang compilation task.
     */
    public static String hardhatConfig() {
        return """
                // DhrLang + Hardhat Integration
                require("@nomicfoundation/hardhat-toolbox");
                
                // Custom DhrLang compilation task
                task("dhrlang:compile", "Compile DhrLang contracts to EVM bytecode")
                  .setAction(async (args, hre) => {
                    const { execSync } = require("child_process");
                    const fs = require("fs");
                    const path = require("path");
                    
                    const contractsDir = path.join(__dirname, "contracts");
                    const outDir = path.join(__dirname, "artifacts", "dhrlang");
                    fs.mkdirSync(outDir, { recursive: true });
                    
                    const files = fs.readdirSync(contractsDir).filter(f => f.endsWith(".dhr"));
                    for (const file of files) {
                      console.log(`Compiling: ${file}`);
                      execSync(`java -jar DhrLang.jar contract compile --output=${outDir} contracts/${file}`);
                    }
                    console.log(`Compiled ${files.length} contract(s) to ${outDir}`);
                  });
                
                task("dhrlang:audit", "Run security audit on DhrLang contracts")
                  .setAction(async () => {
                    const { execSync } = require("child_process");
                    const fs = require("fs");
                    const files = fs.readdirSync("contracts").filter(f => f.endsWith(".dhr"));
                    for (const file of files) {
                      console.log(`Auditing: ${file}`);
                      execSync(`java -jar DhrLang.jar --audit contracts/${file}`, { stdio: "inherit" });
                    }
                  });
                
                /** @type import('hardhat/config').HardhatUserConfig */
                module.exports = {
                  solidity: "0.8.20",
                  networks: {
                    hardhat: {},
                    sepolia: {
                      url: process.env.SEPOLIA_RPC_URL || "",
                      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
                    },
                  },
                  etherscan: {
                    apiKey: process.env.ETHERSCAN_API_KEY || "",
                  },
                };
                """;
    }

    /**
     * Generate a Hardhat deploy script for a DhrLang contract.
     */
    public static String hardhatDeployScript(ContractArtifact artifact) {
        String name = artifact.getContractName();
        return """
                // Deploy %s — auto-generated by DhrLang
                const { ethers } = require("hardhat");
                
                async function main() {
                  const [deployer] = await ethers.getSigners();
                  console.log("Deploying with:", deployer.address);
                  console.log("Balance:", (await deployer.provider.getBalance(deployer.address)).toString());
                
                  // DhrLang-compiled creation bytecode
                  const bytecode = "0x%s";
                  const abi = %s;
                
                  const factory = new ethers.ContractFactory(abi, bytecode, deployer);
                  const contract = await factory.deploy();
                  await contract.waitForDeployment();
                
                  const address = await contract.getAddress();
                  console.log("%s deployed to:", address);
                
                  // Verify on Etherscan (if not local)
                  if (network.name !== "hardhat" && network.name !== "localhost") {
                    console.log("Waiting for block confirmations...");
                    await contract.deploymentTransaction().wait(5);
                    await hre.run("verify:verify", { address });
                  }
                }
                
                main().catch(console.error);
                """.formatted(name, artifact.getCreationBytecodeHex(),
                        artifact.getAbiJson(), name);
    }

    // ═══════════════════════════════════════════════════════════════
    //  TypeScript / Wagmi Bindings
    // ═══════════════════════════════════════════════════════════════

    /**
     * Generate TypeScript contract bindings compatible with wagmi/viem.
     */
    public static String typescriptBindings(ContractArtifact artifact) {
        String name = artifact.getContractName();
        return """
                // %s — auto-generated TypeScript bindings by DhrLang
                // Compatible with wagmi v2 / viem
                
                export const %sABI = %s as const;
                
                export const %sBytecode = "0x%s" as const;
                
                export const %sConfig = {
                  abi: %sABI,
                  bytecode: %sBytecode,
                } as const;
                """.formatted(name,
                name, artifact.getAbiJson(),
                name, artifact.getCreationBytecodeHex(),
                name, name, name);
    }
}
