package dhrlang.debug;

import dhrlang.validation.StorageLayouter;
import dhrlang.validation.StorageLayouter.ContractLayout;
import dhrlang.validation.StorageLayouter.SlotInfo;

import java.util.*;

/**
 * Produces human-readable visualisations of EVM storage layouts
 * generated by {@link StorageLayouter}.
 *
 * <p>All methods are static utilities — no instance state is needed.</p>
 *
 * <h3>Visualisation formats</h3>
 * <ul>
 *   <li>{@link #visualize(ContractLayout)} – full ASCII-table</li>
 *   <li>{@link #visualizeCompact(ContractLayout)} – one-line-per-slot</li>
 *   <li>{@link #visualizeMemoryMap(ContractLayout)} – 32-byte slot map</li>
 *   <li>{@link #visualizeAll(Map)} – multi-contract overview</li>
 * </ul>
 */
public final class StorageLayoutVisualizer {

    /** Standard EVM slot size in bytes. */
    private static final int SLOT_SIZE = 32;

    private StorageLayoutVisualizer() { /* utility */ }

    // ── Full ASCII table ─────────────────────────────────────────────────

    /**
     * Full ASCII-table visualisation of a single contract layout.
     *
     * <pre>
     * ╔══════════════════════════════════════════════════════╗
     * ║  Storage Layout: Token                               ║
     * ╠══════╦═══════════════════╦══════════════╦════════════╣
     * ║ Slot ║ Field             ║ Type         ║ Size       ║
     * ╠══════╬═══════════════════╬══════════════╬════════════╣
     * ║    0 ║ owner             ║ Address      ║  20 bytes  ║
     * ║    1 ║ totalSupply       ║ uint256      ║  32 bytes  ║
     * ╚══════╩═══════════════════╩══════════════╩════════════╝
     * </pre>
     */
    public static String visualize(ContractLayout layout) {
        if (layout == null) return "(null layout)";

        List<SlotInfo> slots = layout.getSlots();
        String name = layout.getContractName();

        // Column widths (minimum values)
        int slotW = 4;
        int fieldW = 6;
        int typeW = 6;
        int sizeW = 10;

        for (SlotInfo s : slots) {
            fieldW = Math.max(fieldW, s.getFieldName().length());
            typeW = Math.max(typeW, s.getFieldType().length());
        }
        slotW = Math.max(slotW, String.valueOf(layout.getTotalSlots()).length());

        // Build table
        int totalW = slotW + fieldW + typeW + sizeW + 13; // separators + padding
        String titleLine = "Storage Layout: " + name;
        totalW = Math.max(totalW, titleLine.length() + 4);

        StringBuilder sb = new StringBuilder();

        // Title bar
        sb.append(topBorder(totalW)).append("\n");
        sb.append("| ").append(padRight(titleLine, totalW - 4)).append(" |\n");
        sb.append(midBorder(slotW, fieldW, typeW, sizeW)).append("\n");

        // Header
        sb.append("| ").append(padRight("Slot", slotW))
          .append(" | ").append(padRight("Field", fieldW))
          .append(" | ").append(padRight("Type", typeW))
          .append(" | ").append(padRight("Size", sizeW))
          .append(" |\n");
        sb.append(midBorder(slotW, fieldW, typeW, sizeW)).append("\n");

        // Rows
        if (slots.isEmpty()) {
            String empty = "(no storage fields)";
            int rowW = slotW + fieldW + typeW + sizeW + 9;
            sb.append("| ").append(padRight(empty, rowW)).append(" |\n");
        } else {
            for (SlotInfo slot : slots) {
                sb.append("| ").append(padLeft(String.valueOf(slot.getSlotIndex()), slotW))
                  .append(" | ").append(padRight(slot.getFieldName(), fieldW))
                  .append(" | ").append(padRight(slot.getFieldType(), typeW))
                  .append(" | ").append(padRight(slot.getSizeInBytes() + " bytes", sizeW))
                  .append(" |\n");
            }
        }

        sb.append(bottomBorder(slotW, fieldW, typeW, sizeW)).append("\n");

        // Summary
        sb.append("Total: ").append(layout.getTotalSlots()).append(" slots, ")
          .append(totalBytes(slots)).append(" bytes used, ")
          .append(layout.getTotalSlots() * SLOT_SIZE).append(" bytes allocated");

        return sb.toString();
    }

    // ── Compact one-liner format ─────────────────────────────────────────

    /**
     * One-line-per-slot compact format.
     *
     * <pre>
     * Token Storage (3 slots):
     *   [0] Address owner          (20 bytes)
     *   [1] uint256 totalSupply    (32 bytes)
     *   [2] mapping balances       (32 bytes)
     * </pre>
     */
    public static String visualizeCompact(ContractLayout layout) {
        if (layout == null) return "(null layout)";

        StringBuilder sb = new StringBuilder();
        sb.append(layout.getContractName()).append(" Storage (")
          .append(layout.getTotalSlots()).append(" slots):\n");

        for (SlotInfo slot : layout.getSlots()) {
            sb.append(String.format("  [%d] %s %s (%d bytes)\n",
                    slot.getSlotIndex(),
                    slot.getFieldType(),
                    slot.getFieldName(),
                    slot.getSizeInBytes()));
        }

        if (layout.getSlots().isEmpty()) {
            sb.append("  (empty)\n");
        }
        return sb.toString();
    }

    // ── Memory map ───────────────────────────────────────────────────────

    /**
     * Visual 32-byte slot map showing byte utilisation.
     *
     * <pre>
     * Memory Map for Token:
     * Slot 0 [################................] owner (20/32 bytes, 62.5%)
     * Slot 1 [################################] totalSupply (32/32 bytes, 100.0%)
     * </pre>
     */
    public static String visualizeMemoryMap(ContractLayout layout) {
        if (layout == null) return "(null layout)";

        StringBuilder sb = new StringBuilder();
        sb.append("Memory Map for ").append(layout.getContractName()).append(":\n");

        for (SlotInfo slot : layout.getSlots()) {
            int used = slot.getSizeInBytes();
            int barLength = 32;
            int filled = Math.min(barLength, (used * barLength) / SLOT_SIZE);
            double pct = (used * 100.0) / SLOT_SIZE;

            sb.append(String.format("Slot %d [", slot.getSlotIndex()));
            sb.append("#".repeat(filled));
            sb.append(".".repeat(barLength - filled));
            sb.append(String.format("] %s (%d/%d bytes, %.1f%%)\n",
                    slot.getFieldName(), used, SLOT_SIZE, pct));
        }

        if (layout.getSlots().isEmpty()) {
            sb.append("(no storage fields)\n");
        }

        return sb.toString();
    }

    // ── Multi-contract overview ──────────────────────────────────────────

    /**
     * Overview of all contract layouts.
     */
    public static String visualizeAll(Map<String, ContractLayout> layouts) {
        if (layouts == null || layouts.isEmpty()) {
            return "(no contract layouts)";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("═══ Storage Layout Overview (")
          .append(layouts.size()).append(" contracts) ═══\n\n");

        int contractNum = 1;
        for (Map.Entry<String, ContractLayout> entry : layouts.entrySet()) {
            sb.append("[").append(contractNum++).append("] ");
            sb.append(visualizeCompact(entry.getValue()));
            sb.append("\n");
        }

        // Total summary
        int totalSlots = 0;
        int totalBytesUsed = 0;
        for (ContractLayout cl : layouts.values()) {
            totalSlots += cl.getTotalSlots();
            totalBytesUsed += totalBytes(cl.getSlots());
        }
        sb.append("Total across all contracts: ").append(totalSlots).append(" slots, ")
          .append(totalBytesUsed).append(" bytes used");

        return sb.toString();
    }

    // ── Slot query helper ────────────────────────────────────────────────

    /**
     * Format a single slot info as a descriptive string.
     */
    public static String describeSlot(SlotInfo slot) {
        if (slot == null) return "(no slot)";
        double utilisation = (slot.getSizeInBytes() * 100.0) / SLOT_SIZE;
        return String.format("Slot %d: %s %s — %d bytes (%.1f%% of 32-byte slot)",
                slot.getSlotIndex(),
                slot.getFieldType(),
                slot.getFieldName(),
                slot.getSizeInBytes(),
                utilisation);
    }

    /**
     * Generate a storage efficiency rating.
     */
    public static String efficiencyRating(ContractLayout layout) {
        if (layout == null || layout.getTotalSlots() == 0) return "N/A (empty)";
        int used = totalBytes(layout.getSlots());
        int allocated = layout.getTotalSlots() * SLOT_SIZE;
        double efficiency = (used * 100.0) / allocated;

        String rating;
        if (efficiency >= 90) rating = "Excellent";
        else if (efficiency >= 70) rating = "Good";
        else if (efficiency >= 50) rating = "Fair";
        else rating = "Poor";

        return String.format("%.1f%% (%s) — %d/%d bytes utilised",
                efficiency, rating, used, allocated);
    }

    // ── Internal helpers ─────────────────────────────────────────────────

    private static int totalBytes(List<SlotInfo> slots) {
        int total = 0;
        for (SlotInfo s : slots) total += s.getSizeInBytes();
        return total;
    }

    private static String padRight(String s, int width) {
        if (s.length() >= width) return s;
        return s + " ".repeat(width - s.length());
    }

    private static String padLeft(String s, int width) {
        if (s.length() >= width) return s;
        return " ".repeat(width - s.length()) + s;
    }

    private static String topBorder(int width) {
        return "+" + "-".repeat(width - 2) + "+";
    }

    private static String midBorder(int slotW, int fieldW, int typeW, int sizeW) {
        return "+" + "-".repeat(slotW + 2)
             + "+" + "-".repeat(fieldW + 2)
             + "+" + "-".repeat(typeW + 2)
             + "+" + "-".repeat(sizeW + 2) + "+";
    }

    private static String bottomBorder(int slotW, int fieldW, int typeW, int sizeW) {
        return midBorder(slotW, fieldW, typeW, sizeW);
    }
}
